name: Comment Trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check for /test in comment
      if: contains(github.event.comment.body, '/test')
      run: echo "Comment contains /test"
