name: Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
    - name: First type
      run: echo "First type ${{ github.event.issue_comment.head.sha }}"
    - name: Second type
      run: echo "Second type ${{ github.event.workflow_run.head_sha }}"
      
  test2:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pull_request = await github.rest.pulls.get({pull_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo})
          response = await github.rest.actions.createWorkflowDispatch({owner: context.repo.owner, repo: context.repo.repo, workflow_id: 'github-actions-demo.yml',ref: 'main',inputs: {'commit-sha': pull_request.data.head.sha, 'pull-request': context.issue.number.toString()}})
          echo $response
        
        
