name: Comment Trigger

on:
  pull_request:
    types: [ opened, synchronize, reopen, edited ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: First type
      run: echo "First type ${{ github.event.pull_request.head.sha }}"
    - name: Second type
      run: echo "Second type ${{ github.event.workflow_run.head_sha }}"
