name: Test Comment

on:
  pull_request_review_comment:
    types: [created]

jobs:
  test_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for /test comment
        uses: actions/github-script@v5
        with:
          script: |
            const { context, github } = require("@actions/github");
            const commentBody = context.payload.comment.body;

            if (commentBody.trim() === "/test") {
              const issueNumber = context.payload.issue.number;
              const repo = context.repo;
              const message = "Running tests...";

              github.rest.issues.createComment({
                ...repo,
                issue_number: issueNumber,
                body: message,
              });
            }
