name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopen, edited ]

jobs:
  trigger_tests:
      runs-on: [ ubuntu-latest ]
      steps:
      - name: Run loop
        run: |
          echo "Therve"
          sleep 30s
          echo "Hetki meni"
        shell: bash
