name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopen, edited ]

jobs:
  trigger_tests:
      runs-on: [ windows-latest ]
      steps:
      - name: Run loop
        run: |
          echo "Therve"
          while($val -ne 3)
          {
              $val++
              Write-Host $val
          }
        shell: powershell
