name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopen, edited ]

jobs:
  trigger_tests:
      runs-on: [ ubuntu-latest ]
      steps:
      - name: Run loop
        run: |
          echo "Therve"
          while [ $x -le 5 ]
          do
            echo "Welcome $x times"
            x=$(( $x + 1 ))
          done
        shell: bash
