name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopen, edited ]

jobs:
 prepare:
    runs-on: [ ubuntu-latest ]
    outputs:
      commit_sha: ${{ steps.variables.outputs.commit_sha }}
    steps:
      - name: Set variables
        id: variables
        run: |
          echo "commit_sha=${{ github.event.pull_request.head.sha }}" >> $env:GITHUB_OUTPUT

      - name: Confirm variables
        run: |
          echo "${{ steps.variables.outputs.commit_sha }}"
