name: Trigger tests

on:
  issue_comment:
    types: [created]

jobs:
  changedfiles:
    runs-on: [ ubuntu-latest ]
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
      - uses: actions/github-script@v6
        id: get-pr
        with:
          github-token: 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
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.rest.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          git diff ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} > mydiff
          git apply mydiff
          echo "mydiff = "
          cat mydiff
        
